name: pkp_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Pinned Dependencies for Stability ---
  # Using specific version constraints prevents unexpected breaking changes.
  dio: ^5.5.0+1
  equatable: ^2.0.5
  get: ^4.6.6 # Pinned to the last stable v4 release to fix dispose() error.
  google_fonts: ^4.0.4
  intl: ^0.19.0

  # Security
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3

  # Network & Connectivity
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1

  # Analytics & Monitoring
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.3+6

  # Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.3.0
  file: ^6.1.4

  # Utils
  logger: ^2.0.2+1
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.8

  # Static Analysis
  dart_code_metrics: ^5.7.6

  # Code Generation
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env.development
    - .env.staging
    - .env.production
