name: pkp_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Pinned Dependencies for Stability ---
  dio: ^5.5.0+1
  # Retrofit client on top of Dio
  retrofit: ^4.4.0
  equatable: ^2.0.5
  get: ^4.6.6 # Pinned to the last stable v4 release to fix dispose() error.
  google_fonts: ^4.0.4
  intl: ^0.19.0
  dotted_border: ^2.1.0 # Added for custom UI elements
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Security
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3

  # Network & Connectivity
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1

  # Analytics & Monitoring
#  firebase_core: ^2.24.2
#  firebase_analytics: ^10.8.0
#  firebase_crashlytics: ^3.4.9
#  firebase_performance: ^0.9.3+6

  # Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.3.0
  file: ^6.1.4

  # Utils
  logger: ^2.0.2+1
  device_info_plus: ^9.1.1
  package_info_plus: ^8.0.2
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.3.0
  geolocator: ^10.1.0
  talker: ^3.2.0
  talker_dio_logger: ^2.2.0
  file_picker: ^8.1.0
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  file_saver: ^0.2.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  # Code Generation
  hive_generator: ^2.0.1
  # Retrofit generator for codegen
  retrofit_generator: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.development
    - .env.staging
    - .env.production

dependency_overrides:
  geolocator_android: ^5.0.2
